const items = [
  { key: "trail", section: "視覺空間 / 執行功能", title: "交替轉換測試", max: 1, instruction: "按 HK-MoCA 題目頁，由開始至完成進行交替連線。", scoring: "正確完成且沒有未更正錯誤得 1 分。", image: "images/trail-making.png" },
  { key: "cube", section: "視覺空間 / 執行功能", title: "複製圖形", max: 1, instruction: "請受測者照住題目頁圖形複製。", scoring: "立體、所有線齊全、沒有額外線、相對線大致平行及長度接近得 1 分。", image: "images/cube.png" },
  { key: "clock", section: "視覺空間 / 執行功能", title: "畫時鐘：十一點十分", max: 3, instruction: "請畫一個時鐘，要寫晒所有數字，並將時間調校到十一點十分。", scoring: "輪廓、數字、時分針各 1 分。", canvas: true },
  { key: "naming", section: "命名", title: "動物命名", max: 3, instruction: "由左至右指出動物圖案，請受測者命名。", scoring: "獅子、犀牛、駱駝 / 單峰駝各 1 分。", animalImages: true },
  { key: "digits", section: "專注力", title: "數字順背及倒背", max: 2, instruction: "順背：2 1 8 5 4；倒背：7 4 2。", scoring: "每一正確數列 1 分；倒背正確答案為 2-4-7。" },
  { key: "tap", section: "專注力", title: "警惕性敲桌", max: 1, instruction: "讀出數字列；當數字「1」出現時，受測者須敲桌。", scoring: "沒有或只有一個錯處得 1 分；兩個或以上錯處得 0 分。" },
  { key: "serial7", section: "專注力", title: "連續 7 減算", max: 3, instruction: "由 100 開始連續減 7：93、86、79、72、65。", scoring: "4-5 個正確得 3 分；2-3 個得 2 分；1 個得 1 分；0 個得 0 分。" },
  { key: "sentence", section: "語言", title: "重複句子", max: 2, instruction: "句子一：姨丈買魚腸。句子二：西施四十四歲。", scoring: "每句完全正確 1 分。" },
  { key: "fluency", section: "語言", title: "語言流暢：動物名稱", max: 1, instruction: "一分鐘內盡量說出動物名稱。", scoring: "正確動物名稱 11 個或以上得 1 分。" },
  { key: "abstract", section: "抽象", title: "相似點", max: 2, instruction: "例題：香蕉－橙。計分題：火車－單車；手錶－間尺。", scoring: "每個抽象類別答案 1 分。" },
  { key: "delayed", section: "延遲記憶", title: "五分鐘後回憶詞語", max: 5, instruction: "不可給提示。詞語：面孔、絲絨、教堂、雛菊、紅色。", scoring: "無提示正確回憶每詞 1 分。" },
  { key: "orientation", section: "定向", title: "日期、星期、地點、地區", max: 6, instruction: "日、月、年、星期、地點、地區。", scoring: "每項正確 1 分。" }
];
let scores = {}; items.forEach(item => scores[item.key] = 0);
let timerInterval = null; let seconds = 0; let chart = null;
function showPage(id) { document.querySelectorAll(".page").forEach(page => page.classList.remove("active")); document.getElementById(id).classList.add("active"); if (id === "result") renderReport(); if (id === "history") renderHistory(); }
function renderAssessment() { const area = document.getElementById("assessmentArea"); area.innerHTML = ""; items.forEach(item => { const div = document.createElement("div"); div.className = "assessment-card"; let buttons = ""; for (let i = 0; i <= item.max; i++) { buttons += `<button onclick="setScore('${item.key}', ${i})" id="${item.key}_${i}">${i}</button>`; } let imageHTML = ""; if (item.image) { imageHTML = `<img src="${item.image}" class="assessment-image" alt="${item.title}" onerror="this.style.display='none'" />`; } if (item.animalImages) { imageHTML = `<div class="moca-image-group"><img src="images/lion.png" alt="lion" onerror="this.style.display='none'" /><img src="images/rhino.png" alt="rhino" onerror="this.style.display='none'" /><img src="images/camel.png" alt="camel" onerror="this.style.display='none'" /></div>`; } if (item.canvas) { imageHTML = `<canvas id="clockCanvas"></canvas><button onclick="clearCanvas()">清除畫板</button>`; } div.innerHTML = `<p class="item-title">${item.section}</p><h3>${item.title} / ${item.max} 分</h3><p>${item.instruction}</p><p class="note"><strong>計分：</strong>${item.scoring}</p>${imageHTML}<div class="score-options">${buttons}</div><textarea id="note_${item.key}" placeholder="答案 / 錯誤類型 / 提示後反應"></textarea>`; area.appendChild(div); }); setupCanvas(); }
function setScore(key, value) { scores[key] = value; updateScore(); autoSave(); const item = items.find(i => i.key === key); for (let i = 0; i <= item.max; i++) document.getElementById(`${key}_${i}`).classList.remove("selected"); document.getElementById(`${key}_${value}`).classList.add("selected"); }
function getTotal() { return Object.values(scores).reduce((sum, value) => sum + Number(value), 0); }
function updateScore() { const total = getTotal(); document.getElementById("totalScore").innerText = total; document.getElementById("percentile").innerText = getPercentile(total); }
function getPercentile(score) { const age = Number(document.getElementById("age").value); const edu = Number(document.getElementById("education").value); if (!age && age !== 0) return "請輸入年齡及教育年數"; if (score <= 20) return "建議跟進（非診斷）"; if (score <= 25) return "建議觀察"; return "正常範圍"; }
function renderReport() { const total = getTotal(); const name = document.getElementById("name").value || "未命名個案"; const englishName = document.getElementById("englishName").value || "-"; const gender = document.getElementById("gender").value || "-"; const age = document.getElementById("age").value || "-"; const education = document.getElementById("education").value || "-"; const assessor = document.getElementById("assessor").value || "-"; const centre = document.getElementById("centre").value || "-"; const date = document.getElementById("date").value || "-"; const percentile = getPercentile(total); document.getElementById("report").innerHTML = `<div class="report-cover"><div class="report-header"><div><h1>HK-MoCA 評估報告</h1><p>Montreal Cognitive Assessment Hong Kong Version</p></div><div class="report-logo">Centre<br>Logo</div></div><hr><div class="report-section"><h2>一、個案基本資料</h2><table class="report-table"><tr><th>中文姓名</th><td>${name}</td><th>英文姓名</th><td>${englishName}</td></tr><tr><th>性別</th><td>${gender}</td><th>年齡</th><td>${age}</td></tr><tr><th>教育年數</th><td>${education}</td><th>評估日期</th><td>${date}</td></tr><tr><th>評估員</th><td>${assessor}</td><th>中心 / 單位</th><td>${centre}</td></tr></table></div><div class="report-section"><h2>二、評估結果摘要</h2><div class="result-box"><div><span>總分</span><strong>${total}/30</strong></div><div><span>百分位 / 分類</span><strong>${percentile}</strong></div></div></div><div class="report-section"><h2>三、各項分數</h2><table class="report-table"><thead><tr><th>範疇</th><th>項目</th><th>分數</th></tr></thead><tbody>${items.map(item => `<tr><td>${item.section}</td><td>${item.title}</td><td>${scores[item.key]} / ${item.max}</td></tr>`).join("")}</tbody></table></div><div class="report-section"><h2>四、備註及專業提醒</h2><div class="warn">此分數只作臨床參考，不能作為診斷的單一標準。認知障礙症診斷需結合臨床病史、客觀認知測試、功能評估、家屬觀察及專業判斷。</div></div><div class="signature-area"><div><p>評估員簽署：</p><div class="signature-line"></div></div><div><p>日期：</p><div class="signature-line"></div></div></div></div>`; drawChart(); }
function collectRecord() { return { name: document.getElementById("name").value, englishName: document.getElementById("englishName").value, gender: document.getElementById("gender").value, age: document.getElementById("age").value, education: document.getElementById("education").value, assessor: document.getElementById("assessor").value, centre: document.getElementById("centre").value, date: document.getElementById("date").value, total: getTotal(), percentile: getPercentile(getTotal()), scores: { ...scores } }; }
function saveRecord() { const records = JSON.parse(localStorage.getItem("moca_records") || "[]"); records.unshift(collectRecord()); localStorage.setItem("moca_records", JSON.stringify(records)); alert("已儲存紀錄"); renderHistory(); }
function renderHistory() { const keyword = document.getElementById("search")?.value?.toLowerCase() || ""; const records = JSON.parse(localStorage.getItem("moca_records") || "[]"); const filtered = records.filter(record => JSON.stringify(record).toLowerCase().includes(keyword)); document.getElementById("historyList").innerHTML = filtered.map((record, index) => `<div class="history-item"><h3>${record.name || "未命名個案"}</h3><p>${record.date || "-"} ｜ ${record.total}/30</p><p>${record.percentile || ""}</p><div class="history-actions"><button onclick="loadRecord(${index})">載入</button><button class="danger" onclick="deleteRecord(${index})">刪除</button></div></div>`).join("") || "<p>未有紀錄</p>"; }
function loadRecord(index) { const records = JSON.parse(localStorage.getItem("moca_records") || "[]"); const record = records[index]; if (!record) return; ["name", "englishName", "gender", "age", "education", "assessor", "centre", "date"].forEach(id => { document.getElementById(id).value = record[id] || ""; }); scores = record.scores || scores; updateScore(); items.forEach(item => { for (let i = 0; i <= item.max; i++) { const btn = document.getElementById(`${item.key}_${i}`); if (btn) btn.classList.remove("selected"); } const selected = document.getElementById(`${item.key}_${scores[item.key]}`); if (selected) selected.classList.add("selected"); }); showPage("result"); }
function deleteRecord(index) { if (!confirm("確定刪除此紀錄？")) return; const records = JSON.parse(localStorage.getItem("moca_records") || "[]"); records.splice(index, 1); localStorage.setItem("moca_records", JSON.stringify(records)); renderHistory(); drawChart(); }
function exportWord() { renderReport(); const content = document.getElementById("report").innerHTML; const html = `<html><head><meta charset="UTF-8"><title>HK-MoCA Report</title></head><body>${content}</body></html>`; const blob = new Blob(["\ufeff", html], { type: "application/msword" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "HK-MoCA_Report.doc"; link.click(); }
function toggleTimer() { if (timerInterval) { clearInterval(timerInterval); timerInterval = null; } else { timerInterval = setInterval(() => { seconds++; const min = String(Math.floor(seconds / 60)).padStart(2, "0"); const sec = String(seconds % 60).padStart(2, "0"); document.getElementById("timer").innerText = `${min}:${sec}`; }, 1000); } }
function resetTimer() { clearInterval(timerInterval); timerInterval = null; seconds = 0; document.getElementById("timer").innerText = "00:00"; }
function toggleDarkMode() { document.body.classList.toggle("dark"); }
function toggleLargeText() { document.body.classList.toggle("large-text"); }
function setupCanvas() { const canvas = document.getElementById("clockCanvas"); if (!canvas) return; const ctx = canvas.getContext("2d"); canvas.width = 900; canvas.height = 400; let drawing = false; function pos(e) { const rect = canvas.getBoundingClientRect(); const point = e.touches ? e.touches[0] : e; return { x: (point.clientX - rect.left) * (canvas.width / rect.width), y: (point.clientY - rect.top) * (canvas.height / rect.height) }; } function start(e) { e.preventDefault(); drawing = true; const p = pos(e); ctx.beginPath(); ctx.moveTo(p.x, p.y); } function end() { drawing = false; ctx.beginPath(); } function draw(e) { if (!drawing) return; e.preventDefault(); const p = pos(e); ctx.lineWidth = 3; ctx.lineCap = "round"; ctx.strokeStyle = "#111827"; ctx.lineTo(p.x, p.y); ctx.stroke(); } canvas.addEventListener("mousedown", start); canvas.addEventListener("mouseup", end); canvas.addEventListener("mousemove", draw); canvas.addEventListener("mouseleave", end); canvas.addEventListener("touchstart", start, { passive: false }); canvas.addEventListener("touchend", end); canvas.addEventListener("touchmove", draw, { passive: false }); }
function clearCanvas() { const canvas = document.getElementById("clockCanvas"); if (!canvas) return; canvas.getContext("2d").clearRect(0, 0, canvas.width, canvas.height); }
function drawChart() { const records = JSON.parse(localStorage.getItem("moca_records") || "[]").slice().reverse(); const ctx = document.getElementById("chart"); if (!ctx) return; if (chart) chart.destroy(); chart = new Chart(ctx, { type: "line", data: { labels: records.map(r => r.date), datasets: [{ label: "HK-MoCA 總分", data: records.map(r => r.total), tension: 0.25 }] }, options: { scales: { y: { min: 0, max: 30 } } } }); }
function autoSave() { localStorage.setItem("moca_draft", JSON.stringify(scores)); }
function clearCurrent() { if (confirm("確定清除目前評估？")) { localStorage.removeItem("moca_draft"); location.reload(); } }
document.getElementById("date").valueAsDate = new Date(); renderAssessment(); updateScore(); renderHistory();
